### ISSUE TITLE
Support for 2023.1

### ISSUE THREAD

**Issue by Josh-Piper** [Nicsilver/JumperTest#2]
Would love if this plugin supported 2023.* versions of Webstorm/JetBrains

I tried doing the upgrade myself but couldn't manage to support previous versions of Java (not a Java dev myself). So the below may or may not be useful. It did work for supporting 2023.1 though.

<img width="1115" alt="CleanShot 2023-03-29 at 12 08 29@2x" src="https://user-images.githubusercontent.com/35862340/228400525-22bc39fa-9e5e-44f1-b6f5-b701dc607447.png">

**Comment by Nicsilver** [comment]
Hey man thanks for this, I'll take a look at this prolly tomorrow or the weekend!

**Comment by Nicsilver** [comment]
So I took a look and jetrbains reports that Webstorm 2020.2 - 2022.3.4 is supported, I see I made a typo in my patch notes saying it supports 2020 which is wrong.

I personally use IntelliJ Ultimate 2023.3.3 as my daily driver IDE and it works for that, which IDE version do you use?
![image](https://user-images.githubusercontent.com/26704528/228656526-847de828-64f6-4e4f-8d11-baa2cb72d179.png)

**Comment by Josh-Piper** [comment]
Can confirm the plugin supported up to 2022.3. Was using it all last year!

But the new release 2023.1 came out a couple days ago, hence the breaking change. :)

**Comment by Nicsilver** [comment]
Ahh right my bad I read it as 2022.1 for some reason my bad 😅

**Comment by Nicsilver** [comment]
Alright the new version is up on the plugin marketplace , ty for the help Joshua :)
